// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client/index.js";
import type {
  AddPetData,
  AddPetResponses,
  DeleteOrderData,
  DeleteOrderErrors,
  DeleteOrderResponses,
  DeletePetData,
  DeletePetErrors,
  DeletePetResponses,
  FindPetsByStatusData,
  FindPetsByStatusResponses,
  FindPetsByTagsData,
  FindPetsByTagsResponses,
  GetInventoryData,
  GetInventoryResponses,
  GetOrderByIdData,
  GetOrderByIdErrors,
  GetOrderByIdResponses,
  GetPetByIdData,
  GetPetByIdErrors,
  GetPetByIdResponses,
  PlaceOrderData,
  PlaceOrderResponses,
  SearchOrdersData,
  SearchOrdersResponses,
  SearchPetsData,
  SearchPetsResponses,
  UpdatePetData,
  UpdatePetErrors,
  UpdatePetResponses,
  UpdatePetWithFormData,
  UpdatePetWithFormErrors,
  UpdatePetWithFormResponses,
  UploadPetImageData,
  UploadPetImageErrors,
  UploadPetImageResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getInventory = <ThrowOnError extends boolean = false>(
  options?: Options<GetInventoryData, ThrowOnError>,
): RequestResult<GetInventoryResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetInventoryResponses, unknown, ThrowOnError>(
    {
      security: [{ name: "api_key", type: "apiKey" }],
      url: "/store/inventory",
      ...options,
    },
  );

export const placeOrder = <ThrowOnError extends boolean = false>(
  options: Options<PlaceOrderData, ThrowOnError>,
): RequestResult<PlaceOrderResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<PlaceOrderResponses, unknown, ThrowOnError>({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/store/order",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const searchOrders = <ThrowOnError extends boolean = false>(
  options: Options<SearchOrdersData, ThrowOnError>,
): RequestResult<SearchOrdersResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<SearchOrdersResponses, unknown, ThrowOnError>(
    {
      security: [{ name: "api_key", type: "apiKey" }],
      url: "/store/order/search",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  );

export const deleteOrder = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOrderData, ThrowOnError>,
): RequestResult<DeleteOrderResponses, DeleteOrderErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteOrderResponses,
    DeleteOrderErrors,
    ThrowOnError
  >({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/store/order/{orderId}",
    ...options,
  });

export const getOrderById = <ThrowOnError extends boolean = false>(
  options: Options<GetOrderByIdData, ThrowOnError>,
): RequestResult<GetOrderByIdResponses, GetOrderByIdErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetOrderByIdResponses,
    GetOrderByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/store/order/{orderId}",
    ...options,
  });

export const addPet = <ThrowOnError extends boolean = false>(
  options: Options<AddPetData, ThrowOnError>,
): RequestResult<AddPetResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AddPetResponses, unknown, ThrowOnError>({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/pet",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const updatePet = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePetData, ThrowOnError>,
): RequestResult<UpdatePetResponses, UpdatePetErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdatePetResponses,
    UpdatePetErrors,
    ThrowOnError
  >({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/pet",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const findPetsByStatus = <ThrowOnError extends boolean = false>(
  options?: Options<FindPetsByStatusData, ThrowOnError>,
): RequestResult<FindPetsByStatusResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    FindPetsByStatusResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/pet/findByStatus",
    ...options,
  });

export const findPetsByTags = <ThrowOnError extends boolean = false>(
  options?: Options<FindPetsByTagsData, ThrowOnError>,
): RequestResult<FindPetsByTagsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    FindPetsByTagsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/pet/findByTags",
    ...options,
  });

export const searchPets = <ThrowOnError extends boolean = false>(
  options: Options<SearchPetsData, ThrowOnError>,
): RequestResult<SearchPetsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<SearchPetsResponses, unknown, ThrowOnError>({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/pet/search",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deletePet = <ThrowOnError extends boolean = false>(
  options: Options<DeletePetData, ThrowOnError>,
): RequestResult<DeletePetResponses, DeletePetErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeletePetResponses,
    DeletePetErrors,
    ThrowOnError
  >({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/pet/{petId}",
    ...options,
  });

export const getPetById = <ThrowOnError extends boolean = false>(
  options: Options<GetPetByIdData, ThrowOnError>,
): RequestResult<GetPetByIdResponses, GetPetByIdErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetPetByIdResponses,
    GetPetByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/pet/{petId}",
    ...options,
  });

export const updatePetWithForm = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePetWithFormData, ThrowOnError>,
): RequestResult<
  UpdatePetWithFormResponses,
  UpdatePetWithFormErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UpdatePetWithFormResponses,
    UpdatePetWithFormErrors,
    ThrowOnError
  >({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/pet/{petId}",
    ...options,
  });

export const uploadPetImage = <ThrowOnError extends boolean = false>(
  options: Options<UploadPetImageData, ThrowOnError>,
): RequestResult<UploadPetImageResponses, UploadPetImageErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UploadPetImageResponses,
    UploadPetImageErrors,
    ThrowOnError
  >({
    security: [{ name: "api_key", type: "apiKey" }],
    url: "/pet/{petId}/uploadImage",
    ...options,
  });
