// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Construct a type with a set of properties K of type T
 */
export type RecordStringNumber = {
  [key: string]: number;
};

export type OrderStatus = "placed" | "approved" | "delivered";

export type Order = {
  id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: string;
  status?: OrderStatus;
  complete?: boolean;
};

export type OrderSearchResults = {
  orders: Array<Order>;
  pagination: {
    totalResults: number;
    totalPages: number;
    pageSize: number;
    page: number;
  };
};

export type DateRange = {
  from?: string;
  to?: string;
};

export type QuantityRange = {
  min?: number;
  max?: number;
};

export type OrderSearchCriteria = {
  orderId?: number;
  petId?: number;
  status?: Array<OrderStatus>;
  complete?: boolean;
  dateRange?: DateRange;
  quantityRange?: QuantityRange;
  sortBy?: "shipDate" | "petId" | "quantity" | "status" | "id";
  sortOrder?: "asc" | "desc";
};

/**
 * Construct a type with a set of properties K of type T
 */
export type RecordStringUnknown = {
  [key: string]: unknown;
};

export type ErrorResponse = {
  message: string;
  details?: RecordStringUnknown;
};

/**
 * Construct a type with a set of properties K of type T
 */
export type RecordStringNever = {
  [key: string]: unknown;
};

export type Category = {
  id?: number;
  name?: string;
};

export type Tag = {
  id?: number;
  name?: string;
};

export type PetStatus = "available" | "pending" | "sold";

export type Pet = {
  id?: number;
  name: string;
  photoUrls: Array<string>;
  category?: Category;
  tags?: Array<Tag>;
  status?: PetStatus;
};

export type PetSearchResults = {
  results: Array<Pet>;
  total: number;
  limit: number;
  offset: number;
  hasMore: boolean;
};

export type PetSearchCriteria = {
  name?: string;
  status?: Array<PetStatus>;
  tags?: Array<string>;
  sortBy?: "name" | "status";
  sortOrder?: "asc" | "desc";
};

export type ApiResponse = {
  code?: number;
  type?: string;
  message?: string;
};

export type GetInventoryData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/store/inventory";
};

export type GetInventoryResponses = {
  /**
   * Ok
   */
  200: RecordStringNumber;
};

export type GetInventoryResponse =
  GetInventoryResponses[keyof GetInventoryResponses];

export type PlaceOrderData = {
  body: Order;
  path?: never;
  query?: never;
  url: "/store/order";
};

export type PlaceOrderResponses = {
  /**
   * Ok
   */
  200: Order;
};

export type PlaceOrderResponse = PlaceOrderResponses[keyof PlaceOrderResponses];

export type SearchOrdersData = {
  body: OrderSearchCriteria;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
  };
  url: "/store/order/search";
};

export type SearchOrdersResponses = {
  /**
   * Ok
   */
  200: OrderSearchResults;
};

export type SearchOrdersResponse =
  SearchOrdersResponses[keyof SearchOrdersResponses];

export type DeleteOrderData = {
  body?: never;
  path: {
    orderId: number;
  };
  query?: never;
  url: "/store/order/{orderId}";
};

export type DeleteOrderErrors = {
  404: ErrorResponse;
};

export type DeleteOrderError = DeleteOrderErrors[keyof DeleteOrderErrors];

export type DeleteOrderResponses = {
  /**
   * Ok
   */
  200: RecordStringNever | unknown;
};

export type DeleteOrderResponse =
  DeleteOrderResponses[keyof DeleteOrderResponses];

export type GetOrderByIdData = {
  body?: never;
  path: {
    orderId: number;
  };
  query?: never;
  url: "/store/order/{orderId}";
};

export type GetOrderByIdErrors = {
  404: ErrorResponse;
};

export type GetOrderByIdError = GetOrderByIdErrors[keyof GetOrderByIdErrors];

export type GetOrderByIdResponses = {
  /**
   * Ok
   */
  200: Order | unknown;
};

export type GetOrderByIdResponse =
  GetOrderByIdResponses[keyof GetOrderByIdResponses];

export type AddPetData = {
  body: Pet;
  path?: never;
  query?: never;
  url: "/pet";
};

export type AddPetResponses = {
  /**
   * Ok
   */
  200: Pet;
};

export type AddPetResponse = AddPetResponses[keyof AddPetResponses];

export type UpdatePetData = {
  body: Pet;
  path?: never;
  query?: never;
  url: "/pet";
};

export type UpdatePetErrors = {
  404: ErrorResponse;
};

export type UpdatePetError = UpdatePetErrors[keyof UpdatePetErrors];

export type UpdatePetResponses = {
  /**
   * Ok
   */
  200: Pet | unknown;
};

export type UpdatePetResponse = UpdatePetResponses[keyof UpdatePetResponses];

export type FindPetsByStatusData = {
  body?: never;
  path?: never;
  query?: {
    status?: PetStatus;
  };
  url: "/pet/findByStatus";
};

export type FindPetsByStatusResponses = {
  /**
   * Ok
   */
  200: Array<Pet>;
};

export type FindPetsByStatusResponse =
  FindPetsByStatusResponses[keyof FindPetsByStatusResponses];

export type FindPetsByTagsData = {
  body?: never;
  path?: never;
  query?: {
    tags?: Array<string>;
  };
  url: "/pet/findByTags";
};

export type FindPetsByTagsResponses = {
  /**
   * Ok
   */
  200: Array<Pet>;
};

export type FindPetsByTagsResponse =
  FindPetsByTagsResponses[keyof FindPetsByTagsResponses];

export type SearchPetsData = {
  body: PetSearchCriteria;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
  };
  url: "/pet/search";
};

export type SearchPetsResponses = {
  /**
   * Ok
   */
  200: PetSearchResults;
};

export type SearchPetsResponse = SearchPetsResponses[keyof SearchPetsResponses];

export type DeletePetData = {
  body?: never;
  path: {
    petId: number;
  };
  query?: never;
  url: "/pet/{petId}";
};

export type DeletePetErrors = {
  404: ErrorResponse;
};

export type DeletePetError = DeletePetErrors[keyof DeletePetErrors];

export type DeletePetResponses = {
  /**
   * Ok
   */
  200: RecordStringNever | unknown;
};

export type DeletePetResponse = DeletePetResponses[keyof DeletePetResponses];

export type GetPetByIdData = {
  body?: never;
  path: {
    petId: number;
  };
  query?: never;
  url: "/pet/{petId}";
};

export type GetPetByIdErrors = {
  404: ErrorResponse;
};

export type GetPetByIdError = GetPetByIdErrors[keyof GetPetByIdErrors];

export type GetPetByIdResponses = {
  /**
   * Ok
   */
  200: Pet | unknown;
};

export type GetPetByIdResponse = GetPetByIdResponses[keyof GetPetByIdResponses];

export type UpdatePetWithFormData = {
  body?: never;
  path: {
    petId: number;
  };
  query?: {
    name?: string;
    status?: PetStatus;
  };
  url: "/pet/{petId}";
};

export type UpdatePetWithFormErrors = {
  404: ErrorResponse;
};

export type UpdatePetWithFormError =
  UpdatePetWithFormErrors[keyof UpdatePetWithFormErrors];

export type UpdatePetWithFormResponses = {
  /**
   * Ok
   */
  200: RecordStringNever | unknown;
};

export type UpdatePetWithFormResponse =
  UpdatePetWithFormResponses[keyof UpdatePetWithFormResponses];

export type UploadPetImageData = {
  body?: never;
  path: {
    petId: number;
  };
  query?: {
    additionalMetadata?: string;
  };
  url: "/pet/{petId}/uploadImage";
};

export type UploadPetImageErrors = {
  404: ErrorResponse;
};

export type UploadPetImageError =
  UploadPetImageErrors[keyof UploadPetImageErrors];

export type UploadPetImageResponses = {
  /**
   * Ok
   */
  200: ApiResponse | unknown;
};

export type UploadPetImageResponse =
  UploadPetImageResponses[keyof UploadPetImageResponses];
