# pyright: reportAttributeAccessIssue=false
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doubler_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "doubler_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x64oubler_service.proto\x12\x0f\x64oubler_service"3\n\rDoubleRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05"4\n\x0e\x44oubleResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x05\x32T\n\x07\x44oubler\x12I\n\x06\x44ouble\x12\x1e.doubler_service.DoubleRequest\x1a\x1f.doubler_service.DoubleResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "doubler_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DOUBLEREQUEST"]._serialized_start = 42
    _globals["_DOUBLEREQUEST"]._serialized_end = 93
    _globals["_DOUBLERESPONSE"]._serialized_start = 95
    _globals["_DOUBLERESPONSE"]._serialized_end = 147
    _globals["_DOUBLER"]._serialized_start = 149
    _globals["_DOUBLER"]._serialized_end = 233
# @@protoc_insertion_point(module_scope)
