# pyright: reportAttributeAccessIssue=false
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import doubler_service_pb2 as doubler__service__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in doubler_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DoublerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Double = channel.unary_unary(
            "/doubler_service.Doubler/Double",
            request_serializer=doubler__service__pb2.DoubleRequest.SerializeToString,
            response_deserializer=doubler__service__pb2.DoubleResponse.FromString,
            _registered_method=True,
        )


class DoublerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Double(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DoublerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Double": grpc.unary_unary_rpc_method_handler(
            servicer.Double,
            request_deserializer=doubler__service__pb2.DoubleRequest.FromString,
            response_serializer=doubler__service__pb2.DoubleResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "doubler_service.Doubler", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "doubler_service.Doubler", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class Doubler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Double(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/doubler_service.Doubler/Double",
            doubler__service__pb2.DoubleRequest.SerializeToString,
            doubler__service__pb2.DoubleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
