// Generated by GPT-5.4 mini.
package com.github.k3karthic.lockall

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.SetProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations
import java.io.ByteArrayOutputStream
import java.io.File
import java.time.Duration
import java.time.Instant
import kotlin.math.max
import javax.inject.Inject

private const val MAX_DEPENDENCY_AGE_DAYS = 365L

abstract class CheckDependencyAgeTask : DefaultTask() {

    @get:Inject
    abstract val execOperations: ExecOperations

    @get:InputFiles
    abstract val lockfiles: ConfigurableFileCollection

    @get:Input
    abstract val directDependencies: SetProperty<String>

    @get:InputDirectory
    abstract val rootDirectory: DirectoryProperty

    @TaskAction
    fun scan() {
        val rootDir = rootDirectory.get().asFile
        val directDependencyCoordinates = directDependencies.get()
        val lockfileFiles = lockfiles.files.sortedBy { it.relativeTo(rootDir).path }

        val staleDependencies = lockfileFiles.flatMap { lockfile ->
            findStaleEntries(lockfile, directDependencyCoordinates, rootDir)
        }

        logger.lifecycle(
            "Scanned ${directDependencyCoordinates.size} direct dependencies across ${lockfileFiles.size} lockfiles."
        )

        if (staleDependencies.isNotEmpty()) {
            val message = buildString {
                appendLine(
                    "Found ${staleDependencies.size} direct dependency lock entries older than $MAX_DEPENDENCY_AGE_DAYS days:"
                )
                staleDependencies.forEach { stale ->
                    appendLine(
                        "- ${stale.lockfile.relativeTo(rootDir).path}: " +
                            "${stale.coordinate.group}:${stale.coordinate.name}:${stale.coordinate.version} " +
                            "last updated ${stale.ageDays} days ago"
                    )
                }
            }
            throw GradleException(message.trimEnd())
        }
    }

    private fun findStaleEntries(
        lockfile: File,
        directDependencies: Set<String>,
        rootDir: File,
    ): List<StaleDependency> {
        val blameTimestamps = gitBlameTimestamps(lockfile, rootDir)
        val fileLines = lockfile.readLines()
        val now = Instant.now()

        return fileLines.mapIndexedNotNull { index, line ->
            val coordinate = line.toDependencyCoordinate() ?: return@mapIndexedNotNull null
            val coordinateKey = coordinate.toCoordinateKey()
            if (coordinateKey !in directDependencies) {
                return@mapIndexedNotNull null
            }

            val lastUpdated = blameTimestamps[index + 1]
                ?: throw GradleException(
                    "Missing git blame metadata for ${lockfile.relativeTo(rootDir).path} line ${index + 1}"
                )
            val ageDays = max(
                0L,
                Duration.between(Instant.ofEpochSecond(lastUpdated), now).toDays()
            )

            if (ageDays > MAX_DEPENDENCY_AGE_DAYS) {
                StaleDependency(lockfile, coordinate, ageDays)
            } else {
                null
            }
        }
    }

    private fun gitBlameTimestamps(lockfile: File, rootDir: File): Map<Int, Long> {
        val relativePath = lockfile.relativeTo(rootDir).path
        val stdout = ByteArrayOutputStream()
        val stderr = ByteArrayOutputStream()

        val result = execOperations.exec {
            commandLine("git", "blame", "--line-porcelain", "--", relativePath)
            workingDir = rootDir
            standardOutput = stdout
            errorOutput = stderr
            isIgnoreExitValue = true
        }

        if (result.exitValue != 0) {
            throw GradleException(
                "Failed to inspect git history for ${relativePath}: ${stderr.toString().trim()}"
            )
        }

        val timestamps = mutableMapOf<Int, Long>()
        var lineNumber = 0
        var currentTimestamp = 0L

        stdout
            .toString()
            .lineSequence()
            .forEach { outputLine ->
                when {
                    outputLine.startsWith("author-time ") -> {
                        currentTimestamp = outputLine.substringAfter(' ').toLong()
                    }

                    outputLine.startsWith("\t") -> {
                        lineNumber += 1
                        timestamps[lineNumber] = currentTimestamp
                    }
                }
            }

        return timestamps
    }

    private fun String.toDependencyCoordinate(): DependencyCoordinate? {
        if (startsWith("#") || isBlank()) {
            return null
        }

        val rawCoordinate = substringBefore("=")
        val parts = rawCoordinate.split(':', limit = 3)
        if (parts.size != 3) {
            return null
        }

        return DependencyCoordinate(parts[0], parts[1], parts[2])
    }

    private fun DependencyCoordinate.toCoordinateKey(): String = "$group:$name:$version"

    private data class DependencyCoordinate(
        val group: String,
        val name: String,
        val version: String,
    )

    private data class StaleDependency(
        val lockfile: File,
        val coordinate: DependencyCoordinate,
        val ageDays: Long,
    )
}
