// Generated by GPT-5.4 mini.
package com.github.k3karthic.lockall

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.SetProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.TaskAction
import java.io.File
import java.time.Duration
import java.time.Instant
import java.time.format.DateTimeFormatter
import java.time.ZonedDateTime
import java.time.ZoneOffset
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import kotlin.math.max

private const val MAX_DEPENDENCY_AGE_DAYS = 365L
private const val MAVEN_CENTRAL_BASE_URL = "https://repo.maven.apache.org/maven2"

abstract class CheckDependencyAgeTask : DefaultTask() {

    @get:InputFiles
    abstract val lockfiles: ConfigurableFileCollection

    @get:Input
    abstract val directDependencies: SetProperty<String>

    @get:InputDirectory
    abstract val rootDirectory: DirectoryProperty

    @TaskAction
    fun scan() {
        val rootDir = rootDirectory.get().asFile
        val directDependencyCoordinates = directDependencies.get()
        val lockfileFiles = lockfiles.files.sortedBy { it.relativeTo(rootDir).path }
        val releaseInstantCache = mutableMapOf<String, Instant>()

        val staleDependencies = lockfileFiles.flatMap { lockfile ->
            findStaleEntries(lockfile, directDependencyCoordinates, releaseInstantCache)
        }

        logger.lifecycle(
            "Scanned ${directDependencyCoordinates.size} direct dependencies across ${lockfileFiles.size} lockfiles."
        )

        if (staleDependencies.isNotEmpty()) {
            val message = buildString {
                appendLine(
                    "Found ${staleDependencies.size} direct dependency lock entries older than $MAX_DEPENDENCY_AGE_DAYS days:"
                )
                staleDependencies.forEach { stale ->
                    appendLine(
                        "- ${stale.lockfile.relativeTo(rootDir).path}: " +
                            "${stale.coordinate.group}:${stale.coordinate.name}:${stale.coordinate.version} " +
                            "released on ${stale.publishedAt.atZone(ZoneOffset.UTC).toLocalDate()} " +
                            "(${stale.ageDays} days ago)"
                    )
                }
            }
            throw GradleException(message.trimEnd())
        }
    }

    private fun findStaleEntries(
        lockfile: File,
        directDependencies: Set<String>,
        releaseInstantCache: MutableMap<String, Instant>,
    ): List<StaleDependency> {
        val fileLines = lockfile.readLines()
        val now = Instant.now()

        return fileLines.mapNotNull { line ->
            val coordinate = line.toDependencyCoordinate() ?: return@mapNotNull null
            val coordinateKey = coordinate.toCoordinateKey()
            if (coordinateKey !in directDependencies) {
                return@mapNotNull null
            }

            val publishedAt = dependencyReleaseInstant(coordinate, releaseInstantCache)
            val ageDays = max(0L, Duration.between(publishedAt, now).toDays())

            if (ageDays > MAX_DEPENDENCY_AGE_DAYS) {
                StaleDependency(lockfile, coordinate, publishedAt, ageDays)
            } else {
                null
            }
        }
    }

    private fun dependencyReleaseInstant(
        coordinate: DependencyCoordinate,
        releaseInstantCache: MutableMap<String, Instant>,
    ): Instant {
        val cacheKey = coordinate.toCoordinateKey()
        releaseInstantCache[cacheKey]?.let { return it }

        val releaseUrl = mavenCentralReleaseUrl(coordinate)
        val response = newHttpClient().send(
            HttpRequest.newBuilder(URI.create(releaseUrl))
                .GET()
                .header("accept", "application/xml,application/octet-stream;q=0.9,*/*;q=0.8")
                .header("user-agent", "dependency-age-checker")
                .build(),
            HttpResponse.BodyHandlers.discarding(),
        )

        if (response.statusCode() != 200) {
            throw GradleException(
                "Failed to determine release date for ${coordinate.group}:${coordinate.name}:${coordinate.version} " +
                    "from ${releaseUrl}: HTTP ${response.statusCode()}"
            )
        }

        val lastModified = response.headers().firstValue("Last-Modified")
            .orElseThrow {
                GradleException(
                    "Missing Last-Modified header for ${coordinate.group}:${coordinate.name}:${coordinate.version} " +
                        "at ${releaseUrl}"
                )
            }

        return ZonedDateTime.parse(lastModified, DateTimeFormatter.RFC_1123_DATE_TIME)
            .toInstant()
            .also { releaseInstantCache[cacheKey] = it }
    }

    private fun String.toDependencyCoordinate(): DependencyCoordinate? {
        if (startsWith("#") || isBlank()) {
            return null
        }

        val rawCoordinate = substringBefore("=")
        val parts = rawCoordinate.split(':', limit = 3)
        if (parts.size != 3) {
            return null
        }

        return DependencyCoordinate(parts[0], parts[1], parts[2])
    }

    private fun DependencyCoordinate.toCoordinateKey(): String = "$group:$name:$version"

    private fun mavenCentralReleaseUrl(coordinate: DependencyCoordinate): String {
        val groupPath = coordinate.group.replace('.', '/')
        return buildString {
            append(MAVEN_CENTRAL_BASE_URL)
            append('/')
            append(groupPath)
            append('/')
            append(coordinate.name)
            append('/')
            append(coordinate.version)
            append('/')
            append(coordinate.name)
            append('-')
            append(coordinate.version)
            append(".pom")
        }
    }

    private data class DependencyCoordinate(
        val group: String,
        val name: String,
        val version: String,
    )

    private data class StaleDependency(
        val lockfile: File,
        val coordinate: DependencyCoordinate,
        val publishedAt: Instant,
        val ageDays: Long,
    )

    private fun newHttpClient(): HttpClient =
        HttpClient.newBuilder()
            .followRedirects(HttpClient.Redirect.NORMAL)
            .build()
}
