# https://github.com/detekt/detekt/blob/v2.0.0-alpha.6/detekt-core/src/main/resources/default-detekt-config.yml

complexity:
  CyclomaticComplexMethod:
    allowedComplexity: 10
  CognitiveComplexMethod:
    active: true
    allowedComplexity: 15
  ComplexCondition:
    allowedConditions: 5
  LongMethod:
    allowedLines: 50
  LongParameterList:
    allowedFunctionParameters: 5
    allowedConstructorParameters: 5
